global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'client-service'
    static_configs:
      - targets: ['client-service:8080']
    metrics_path: /q/metrics

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8080']
    metrics_path: /q/metrics

  - job_name: 'dispatch-service'
    static_configs:
      - targets: ['dispatch-service:8080']
    metrics_path: /q/metrics
